apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
spec:
    capacity:
        storage: 3Gi
    accessModes:
        - ReadWriteOnce
    local:
      path: /app/data
    nodeAffinity:
      required:
        nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                   - node1
