apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
spec:
    storageClassName: local-path
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
        storage: 3Gi