apiVersion: v1
kind: Pod
metadata:
  name: my-prod
  labels:
    role: my-prod
spec:
  containers:
    - name: my-prod
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: "/app/data"
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-claim
  