apiVersion: v1
kind: Pod
metadata:
  name: my-prod
  labels:
    role: my-prod
spec:
  containers:
    - name: my-prod
      image: nginx
      volumeMounts:
        - name: web-data
          mountPath: /app/config
  volumes:
    - emptyDir: {}
      name: web-data
    - name: default-token-2fp89
      secret:
        secretName: 490b1b1b-0b1b-4b1b-9b1b-0b1b1b1b1b1b
  