apiVersion: v1
kind: Pod
metadata:
  name: my-prod
  labels:
    role: my-prod
spec:
  containers:
    - name: my-prod
      image: nginx
      volumeMounts:
        - name: web-data
          mountPath: /app/config
  volumes:
    - emptyDir: {}
      name: web-data
  