apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    role: hello
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: hello
      image: tonachheun/hello:latest
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        privileged: false
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
  restartPolicy: Always
  