apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    role: hello
spec:
  containers:
    - name: hello
      image: tonachheun/hello:latest
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  