apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    role: hello
spec:
  containers:
    - name: hello
      image: tonachheun/hello:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
  restartPolicy: Always
  