apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: default
spec:
    limits:
    - min:
        cpu: 500m
        memory: 250Mi
      max:
        cpu: 2
        memory: 2Gi
      default:
        cpu: 500m
        memory: 500Mi
      defaultRequest:
        cpu: 250m
        memory: 250Mi
      type: Container
